### ISSUE TITLE
GUI does not open

### ISSUE THREAD

**Issue by devsnek** [wgurecky/pyReactor#2]
I installed all the dependancies with no errors, but when i run pyReactor, it seems to be running, but there is no GUI.
![screen shot 2016-02-23 at 2 02 36 pm](https://cloud.githubusercontent.com/assets/5952481/13264944/209e10e8-da36-11e5-8f72-9060ec0e6304.png)
It just stays like this until I CTRL-C and then it gives a bunch of errors related to keyboard interrupts and such.
Any help would be great.

**Comment by devsnek** [comment]
Follow up:
`swig/python detected a memory leak of type 'wxPyXmlSubclassFactory *', no destructor found.` is thrown when I quit

**Comment by wgurecky** [comment]
Unfortunately, I do not have a Mac to test on :(.  Did you install wxPython through .dmg or by using homebrew?

try homebrew:  

`brew install wxpython`

As for the memory leak in wxPy, this may be a bug in wxPython3.0:
comments.gmane.org/gmane.comp.lib.wxwidgets.devel/153770
